name: 游냍 Bug Report
description: Rapportera ett problem med Cursor+Loveable Toolkit
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Tack f칬r att du tar dig tid att rapportera ett problem! 
        Fyll i informationen nedan s친 noggrant som m칬jligt.

  - type: dropdown
    id: environment
    attributes:
      label: Utvecklingsmilj칬
      options:
        - macOS
        - Windows
        - Linux
        - Annan (specificera i beskrivningen)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "t.ex. v16.14.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      options:
        - React
        - Next.js
        - Vue.js
        - Angular
        - Annan (specificera i beskrivningen)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problembeskrivning
      description: Beskriv problemet s친 detaljerat som m칬jligt
      placeholder: "N칛r jag k칬r [kommando] s친 h칛nder [problem]..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steg f칬r att reproducera
      description: Lista exakta steg f칬r att reproducera problemet
      placeholder: |
        1. K칬r `npm run ...`
        2. 칐ppna filen ...
        3. Klicka p친 ...
        4. Se felmeddelande ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: F칬rv칛ntat beteende
      description: Vad f칬rv칛ntade du dig skulle h칛nda?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevanta loggar eller felmeddelanden
      description: Kopiera och klistra in relevanta loggar. Detta formateras automatiskt som kod.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Ytterligare kontext
      description: L칛gg till annan relevant kontext om problemet h칛r
      placeholder: "t.ex. projektstruktur, konfigurationsfiler, etc."
