name: 游닀 Documentation Improvement
description: F칬resl친 f칬rb칛ttringar eller rapportera problem med dokumentationen
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Tack f칬r att du hj칛lper oss f칬rb칛ttra dokumentationen!
        Din feedback hj칛lper andra utvecklare att anv칛nda toolkiten effektivt.

  - type: dropdown
    id: doc_type
    attributes:
      label: Typ av dokumentation
      options:
        - README.md
        - INSTALLATION.md
        - CONTRIBUTING.md
        - TROUBLESHOOTING.md
        - COST_OPTIMIZATION.md
        - CUSTOMIZATION.md
        - Kod kommentarer
        - Annan (specificera nedan)
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Plats i dokumentationen
      description: L칛nka till eller beskriv var i dokumentationen problemet finns
      placeholder: "t.ex. README.md, sektion 'Quick Start'"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Nuvarande inneh친ll
      description: Vad st친r det i dokumentationen nu?
      placeholder: "Kopiera relevant text eller beskriv nuvarande inneh친ll"

  - type: textarea
    id: suggestion
    attributes:
      label: F칬reslagen f칬rb칛ttring
      description: Hur skulle du vilja f칬rb칛ttra denna del av dokumentationen?
      placeholder: "t.ex. L칛gg till exempel f칬r Windows anv칛ndare..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Motivering
      description: Varf칬r skulle denna 칛ndring vara hj칛lpsam?
      placeholder: "Detta skulle hj칛lpa eftersom..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Bekr칛ftelse
      description: Genom att skicka in detta f칬rslag bekr칛ftar du att
      options:
        - label: Jag har kontrollerat att detta inte 칛r en dubblett av ett existerande f칬rslag
          required: true
        - label: Jag 칛r villig att hj칛lpa till med implementationen av denna f칬rb칛ttring
          required: false
