name: 游눠 Feature Request
description: F칬resl친 en ny funktion f칬r Cursor+Loveable Toolkit
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Tack f칬r ditt intresse att f칬rb칛ttra Cursor+Loveable Toolkit!
        Beskriv din id칠 s친 detaljerat som m칬jligt nedan.

  - type: textarea
    id: problem
    attributes:
      label: Relaterat problem
      description: Beskriv problemet som din feature skulle l칬sa
      placeholder: "Jag blir frustrerad n칛r..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: F칬reslagen l칬sning
      description: Beskriv l칬sningen du skulle vilja se
      placeholder: "Det skulle vara bra om toolkiten kunde..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativ du 칬verv칛gt
      description: Beskriv alternativa l칬sningar eller features du 칬verv칛gt
      placeholder: "Jag har ocks친 t칛nkt p친 att..."

  - type: dropdown
    id: impact
    attributes:
      label: P친verkan p친 kostnad/prestanda
      description: Hur skulle denna feature p친verka toolkit's resursanv칛ndning?
      options:
        - Minimal p친verkan
        - Liten 칬kning i resurser/kostnad
        - Moderat 칬kning
        - Betydande 칬kning
        - Os칛ker
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Upplevd prioritet
      options:
        - Kritisk (blockerar arbete)
        - H칬g (p친verkar produktivitet)
        - Medium (skulle vara v칛rdefull)
        - L친g (nice to have)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Ytterligare kontext
      description: L칛gg till sk칛rmdumpar, kodexempel eller annan kontext h칛r
      placeholder: "t.ex. mockups, exempel p친 implementation, etc."
